export const stockData = [
    {
        id: "1",
        login: "Lorem",
        name: "Lorem",
        lastName: "Ipsum",
        email: "Lorem@gmail.com",
    },
    {
        id: "2",
        login: "Lorem",
        name: "Lorem",
        lastName: "Ipsum",
        email: "Lorem@gmail.com",
    },
    {
        id: "3",
        login: "Lorem",
        name: "Lorem",
        lastName: "Ipsum",
        email: "Lorem@gmail.com",
    },
    {
        id: "4",
        login: "Lorem",
        name: "Lorem",
        lastName: "Ipsum",
        email: "Lorem@gmail.com",
    },
    {
        id: "5",
        login: "Lorem",
        name: "Lorem",
        lastName: "Ipsum",
        email: "Lorem@gmail.com",
    },
    {
        id: "6",
        login: "Lorem",
        name: "Lorem",
        lastName: "Ipsum",
        email: "Lorem@gmail.com",
    },
    {
        id: "7",
        login: "Lorem",
        name: "Lorem",
        lastName: "Ipsum",
        email: "Lorem@gmail.com",
    },
    {
        id: "8",
        login: "Lorem",
        name: "Lorem",
        lastName: "Ipsum",
        email: "Lorem@gmail.com",
    },
    {
        id: "9",
        login: "Lorem",
        name: "Lorem",
        lastName: "Ipsum",
        email: "Lorem@gmail.com",
    },
    {
        id: "10",
        login: "Lorem",
        name: "Lorem",
        lastName: "Ipsum",
        email: "Lorem@gmail.com",
    },
];